require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 4.2
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'config/deploy.rb'
    # below added temporarily to hold back effects of version upgrade
    - 'app/views/search/*'
    - 'lib/tasks/*'

Rails:
  Enabled: true

Lint/UnusedBlockArgument:
  Exclude:
    - 'config/initializers/hydra_config.rb'
    - 'spec/**/*'

#Metrics/AbcSize:
#  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/LineLength:
  Enabled: true
  Max: 200

Metrics/MethodLength:
  Enabled: true
  Max: 14

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/SymbolProc:
  Exclude:
    - 'spec/factories/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Layout/IndentHash:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Layout/LeadingCommentSpace:
  Exclude:
    - 'spec/**/*'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/GlobalVars:
  Exclude:
    - 'config/initializers/redis_config.rb'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/javascripts/jasmine_spec.rb'
    - 'spec/tasks/rake_spec.rb'
    - 'spec/jobs/event_jobs_spec.rb'
    - 'spec/abilities/**/*'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/inputs/**/*'

# disable (temporarily, one hopes?) new cops acquired in the version upgrade
Capybara/CurrentPathExpectation:
  Enabled: true

Capybara/FeatureMethods:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'
    - 'Guardfile'

Naming/VariableNumber:
  Enabled: true

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: true
  Max: 20

RSpec/ExpectInHook:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  Max: 8

RSpec/NestedGroups:
  Enabled: true
  Max: 5

Security/YAMLLoad:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

